### ISSUE TITLE
JSON parsing issues in various methods

### ISSUE THREAD

**Issue by timothyparez** [TrekDev/net-ipfs-api#16]
Taking `Swarm.Peers` for example:

    public async Task<ICollection<MultiAddress>> Peers(CancellationToken cancellationToken = 
    default(CancellationToken))
    {
        HttpContent content = await ExecuteGetAsync("peers", cancellationToken);
        string json = await content.ReadAsStringAsync();
        var swarmPeers = _jsonSerializer.Deserialize<IDictionary<string, IList<string>>>(json);
        return swarmPeers
            .SelectMany(x => x.Value)
            .Select(x => new MultiAddress(x)).ToArray();
    }

The JSON response (returned by 0.4.9) cannot
actually be deserialized as `IDictionary<string, IList<string>>`

Trying to do so results in the following exception:

    Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while 
    parsing value: {. Path 'Peers', line 1, position 11.'

If, as a means to test this theory, you simply use the non-generic version of `Deserialize`:

    var result = JsonConvert.DeserializeObject(json, _settings);

No exception will be thrown.
And another way to test the theory:

    public class PeerCollection
    {
        public PeerEntry[] Peers { get; set; }
    }
    
    public class PeerEntry
    {
        public string Addr { get; set; }
        public string Peer { get; set; }
        public string Latency { get; set; }
        public string Muxer { get; set; }
        public object Streams { get; set; }
    }

    //Deserializing to the types above:
    var result = JsonConvert.DeserializeObject<PeerCollection>(json, _settings);

This also completes without exceptions.

**Comment by TrekDev** [comment]
Hi @timothyparez. Do you know if this is caused by the new IPFS version? I don't remember this happening with previous versions.

**Comment by timothyparez** [comment]
Going to check that. 

I'm also checking compatibility between the `PeerEntry` class above and the `MultiAddress` class
since the JSON can be directly converted to proper instances of `PeerEntry` I'm not sure why
it's currently relying on splitting strings (but I might not understand the full scope here):

        public MultiAddress(string uriString)
        {
            OriginalString = uriString;
            _components = OriginalString.Split('/');
        }

**Comment by timothyparez** [comment]
I tested 0.4.9 just now (was testing 0.4.10 before)
    {"Version":"0.4.9","Commit":"","Repo":"5","System":"amd64/windows","Golang":"go1.8.1"}

The result is the same exception.

It returns the following JSON [Pasted on Pastebin](https://pastebin.com/Dja0613S )

If you paste the JSON in Visual Studio using `Edit/Paste Special/Paste JSON as classes`  
you'll end up with something like the classes in the original post which can be used to
deserialize the JSON to show that it's actually valid.

I'm not sure about older versions because I only started using it when 0.4.9 was released.

**Comment by TrekDev** [comment]
Thanks for the JSON sample. I definitely don't remember that `Muxer` field but it's been a while since I looked at the raw output. I'll have a go at it over the weekend.

**Comment by timothyparez** [comment]
In case you don't like creating classes only to deserialize and would like to avoid working
with strings but rather let JsonConvert do the hard work you could use `dynamic` instead:

    var json = "jsonstringhere";
    var results = JsonConvert.DeserializeObject<dynamic>(json);
    IEnumerable<dynamic> jsonPeers = results.Peers;

    var peers = jsonPeers.Select(x => new MultiAddress
    {
        Address = x.Addr.ToString(),
        Peer = x.Peer.ToString(),
        Latency = x.Latency.ToString(),
        Muxer = x.Muxer.ToString(),
        Streams = x.Streams.ToString()
    });

The code above results in the following:

![image](https://user-images.githubusercontent.com/2060470/28359189-00dbb01a-6ca4-11e7-9099-f79c8f71f48e.png)

Note that I quickly created an empty `MultiAddress` class specifically for this example.
The idea would be you convert directly from the json to the real `MultiAddress` class in the project.
If they added fields in the future things would just keep working.
