### ISSUE TITLE
ipfs.Object.Put trouble

### ISSUE THREAD

**Issue by slothbag** [TrekDev/net-ipfs-api#2]
I'm having trouble using ipfs.Object.Put

I am constructing a json merkledag document, with Data and Link properties. But using this library IPFS daemon always returns 400 bad request.

Could there be an issue with the text encoding, like UTF8/Unicode/Ascii or something like that?  Have you tried using the Object Put call? Any tips to get it working?

Cheers

**Comment by slothbag** [comment]
The only thing I can see is the Put method is using ExecuteGetAsync instead of ExecutePostAsync.. will keep tinkering with it.

**Comment by TrekDev** [comment]
Hi slothbag, I'll have a look at this today.

Can you give me an example of how you're using it? Like, what arguments/options you're using.

Thanks,

-TD

**Comment by slothbag** [comment]
I am creating a MerkleDag JSON string manually and then want to upload it using ipfs object put.

I wrote my own MerkleDag class but could probably re-use yours.. not a big deal.

I have submitted a PR for the issue... you might be able to use it to get a head start :) #3

**Comment by TrekDev** [comment]
Hi @slothbag, I've committed 4b95e6d, currently on the `develop` branch which fixes this.

Sorry I couldn't use your pull request, but it was on the master branch. I've added a contributions section to the README for future reference. I've added comment/thanks in code/readme crediting you with the snippet.

**Comment by slothbag** [comment]
No drama.  I wasn't sure if you were gonna use it anyway. Just thought it might help :)

Next time i'll submit against develop.  Thanks for fixing.

**Comment by TrekDev** [comment]
Thanks for the snippet and finding the issue, saved me from fiddling with it whilst I was looking at the JsonSerialization & tests. I'll probably need to spend a weekend or two making it more robust like I did with EthClient.NET before it's really usable.

**Comment by slothbag** [comment]
I don't really want to open another issue for this..  I have a branch https://github.com/slothbag/net-ipfs-api/tree/xamarin that includes a folder for a Xamarin project. I cant open your versions in Xamarin because of incompatible project types.

Feel free to merge this, otherwise i'll happily track along with your develop branch.

**Comment by TrekDev** [comment]
Hmm... That's weird. I setup the PCL with framework version Profile111, which should target Xamarin iOS/Android. Can you tell me which profile number it should be?

**Comment by slothbag** [comment]
The compiled dll is probably compatible to by included/used by Xamarin, but Xamarin Studio the IDE cannot open the .csproj file for this project.  XS can only handle the most basic traditional .csproj files, files created by newer versions of Visual Studio XS doesn't know how to open.

If that makes sense :)  By the way i'm not developing for Android or anything, I just don't like VS :)

**Comment by TrekDev** [comment]
Ah right. Do you know what xml tags it's having problems with? I could remove them.

**Comment by slothbag** [comment]
There was many errors, it had various problems with the tests project and I think it had issues with the ProjectTypeGuids. If I delete them then I have to recreate the project basically.  

Don't worry about it.. more trouble than its worth. I'll just keep a XS modified repo.

**Comment by TrekDev** [comment]
Ok. Yes, I know Xamarin Studio has always had problems with MS Test projects. I may look into converting it to NUnit tests with a plugin we used to use when we used Xamarin at work.
