### ISSUE TITLE
IpfsClient.Cat("...") throws OutOfMemoryException on larger files

### ISSUE THREAD

**Issue by timothyparez** [TrekDev/net-ipfs-api#21]
When using `IpfsClient.Cat(string ipfsPath)` to download larger files (~>200mb on my system)  
it throws an `OutOfMemoryException` and bugs out.

(v0.4.10)

**Comment by timothyparez** [comment]
Turns out the exception is caused by

**IpfsCommand.cs line 86**:
`HttpResponseMessage response = await _httpClient.SendAsync(request, cancellationToken);`

The `SendAsync` method has an override that takes an argument of the type [HttpCompletionOption](https://msdn.microsoft.com/en-us/library/system.net.http.httpcompletionoption(v=vs.118).aspx).

The default value for this argument is `ResponseContentRead` which means the operation
only completes after all the content has been read and loaded into memory. 
For most commands this isn't an issue, except when we `cat` larger files.

The alternative is to use `HttpClient.GetStreamAsync` which gives us direct access to  
the stream which we can then read from and write whatever we read directly to a file.

   using(var catStream = await _httpClient.GetStreamAsync(request.RequestUri))
   {
        //Read fromt he buffer, copy to file or something...
   }

This avoids the `OutOfMemoryException` but doesn't fit in the current model.
So instead, maybe, we just handle `Cat` as  a unique situation.

**Comment by timothyparez** [comment]
I'm working on the fix right now.

**Comment by TrekDev** [comment]
Big thanks @timothyparez, merged pull request, will merge into master ASAP.
