### ISSUE TITLE
Unbale to get pdf file 

### ISSUE THREAD

**Issue by nayan2** [TrekDev/net-ipfs-api#30]
ipfs.Cat does't work for pdf file while it is perfectly fine with text file. a test pdf file  hash = "QmWPCRv8jBfr9sDjKuB5sxpVzXhMycZzwqxifrZZdQ6K9o". ipfs cat return stream content which doesnt match with my originial pdf file content ...

**Comment by timothyparez** [comment]
Hi, 
I just tested with the following code:

```
using (var client = new IpfsClient())
{
    using (var stream = await client.Cat("QmWPCRv8jBfr9sDjKuB5sxpVzXhMycZzwqxifrZZdQ6K9o"))
    using (var fileStream = File.OpenWrite("d:\\output.pdf"))
    {
        await stream.CopyToAsync(fileStream);                    
    }
}
```

And I get the original PDF file as a result.
Can you show us your code?
