### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [TrekDev/net-ipfs-api#32]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by timothyparez** [comment]
Sounds good to me. @jeremy-ellis-tech what do you think?

**Comment by jeremy-ellis-tech** [comment]
Sounds good to me :+1:

**Comment by jeremy-ellis-tech** [comment]
Done. I've also changed my github name since creation of this project. Old links will still be forwarded but if anyone with access could update those in the client list for clarity that would be fantastic, thanks.

**Comment by daviddias** [comment]
Updated here https://github.com/ipfs/ipfs/commit/3d7dd30cef49e3d8d5bbbb9621fbd5c8daba1719, thank you!
