### ISSUE TITLE
Object.Put serialization bug

### ISSUE THREAD

**Issue by slothbag** [TrekDev/net-ipfs-api#4]
Hi TD, I just updated to this latest develop, now it seems the MerkleNode is serializing the "Data" byte array to a Base64 string..  Normally I just send some plain text in the Data property and then in IPFS webui I can see the data in the UI.. now all I can see is Base64 text.

**Comment by TrekDev** [comment]
Yes, I was under the impression that the data field was for arbitrary data, pictures/videos etc. so byte[] would be the most appropriate way to hold that, is that not the case?

Can you tell me what webui you're using?

**Comment by slothbag** [comment]
Yes, I think you're right, the data field is for arbitrary data.  You could store raw bytes (not sure how via json), a plain text string, or a base64 encoded message..

Currently your MerkleNode serializer is forcing Base64 encoded string for everything. ( I think this is Json.Net default for Byte arrays )

Sure, the WebUI is the one that comes with IPFS http://127.0.0.1:5001/webui

**Comment by slothbag** [comment]
I'm not sure of the best approach to fix.. Because you want Data to be a byte array in your MerkleNode class.. but you want to do something like serialize as Encoding.UTF8.GetString(data) just for Object.Put (JSON) purposes.. perhaps Object.Put (ProtoBuf) can send raw bytes???

**Comment by TrekDev** [comment]
Yes, Json.NET's default serializer for byte[]'s is base64.

I don't think you could store raw bytes with json since json only defines key-value pairs as strings, null, array, true false values etc. So it'll have to be serialized to some kind of string. I'm looking into adding protobuf support this weekend, which might help.

I think the easiest way to deal with strings -> bytes is if you use Encoding.UTF8.GetBytes("my string"); and Decode with Encoding.UTF8.GetString(myByteArray);

**Comment by TrekDev** [comment]
I think a way around would be for you to define your own custom `IJsonSerializer` and inject it into the constructor: 

`public IpfsClient(Uri address, HttpClient httpClient, IJsonSerializer jsonSerializer)`

You can use the one I've written for all the other calls and override the serialization for MerkleNode's for that specific case.

**Comment by slothbag** [comment]
Thanks, that's a good idea. I'll inject my own serializer.

Though I still think having default Base64 encoding is still confusing given the Data field can store anything.

For example.. If I import an existing MerkleNode generated elsewhere from IPFS and it contains some raw bytes, when I use net-ipfs-api to write that MerkleNode back to IPFS it will get a different hash because it will convert those bytes to a Base64 encoded string.

**Comment by TrekDev** [comment]
Ah, right, good point. Do you know how ipfs serializes arbitrary data if you add it through the CLI for example?

**Comment by slothbag** [comment]
No, I just asked the guys on IRC.. but its a bit of a ghost town there lately.

I suspect the Object.Put JSON CLI version might be restricted to only adding plain text.. but im just guessing

**Comment by TrekDev** [comment]
Unfortunately that could be the case. I tried using the CLI object commands with the cat jpg from the alpha showcase: `QmajFHHivh25Qb2cNbnnnEeUe1gDLHX9ta7hs2XKX1vazb`. Using `ipfs object data <hash>` shows unprintable characters, so I'm pretty sure it can't be added like that.

**Comment by TrekDev** [comment]
Although `ipfs object get <hash>` return this: `{"Links":[],"Data":"\u0008\u0002\u0012��\u000..."` so it's possible the \u00... formatting is needed.

**Comment by TrekDev** [comment]
This ipfs issue might be of interest: https://github.com/ipfs/go-ipfs/issues/1582

**Comment by slothbag** [comment]
I'm not familiar with the \u00 formatting.  But yeah, I have seen that in output.

**Comment by slothbag** [comment]
Ideally the Object.Put (JSON version) should just accept base64 and convert it back to raw bytes internally to IPFS.

**Comment by TrekDev** [comment]
Yes.

Just out of curiosity, do you know what the difference is between this and ipfs add "<file>"? Does this give you a finer level of control?

**Comment by slothbag** [comment]
My understanding is `ipfs add` takes a file or folder (filesystem object) and wraps it in the merkledag format to represent the file/folders as IPFS knows it.

I want to use the same merkledag format to wrap up my custom data, so not necessarily a filesystem structure but a similar tree structure.

`ipfs object put` allows you to construct the merkle dag yourself, otherwise I would have to put all my data into a filesystem and then add it..

**Comment by TrekDev** [comment]
Ok. Just wondering, since you can add arbitrary data with `Ipfs.Add(myIpfsStream)` couldn't you use that? Where you can build `IpfsStream` with a `MemoryStream` pointing to a `byte[]`

**Comment by slothbag** [comment]
Can that create custom merkledag objects or just add a file (auto wrapped in a merkledag)?  Getting hard to conceptually wrap my head around this stuff :(

**Comment by TrekDev** [comment]
`ipfsClient.Add(myIpfsStream)` wraps the contents of whatever your stream points to. The stream doesn't have to be a `FileStream`, it could be a `MemoryStream` pointing to a `byte` array, so it could be arbitrary data, not relying on  whatever file system you use.

**Comment by slothbag** [comment]
But my content needs to be broken up into a tree of merkle dags.  So I need to start at the bottom, generate the lowest level, get its hash, generate the next node up and place in its "Links" section of the DAG put the hash from the lower dag. All the way up.

**Comment by TrekDev** [comment]
Right, sorry then, you're right, you'll need Object put then.

**Comment by slothbag** [comment]
Well I tried to copy & paste 150 lines of JsonSerializer classes from net-ipfs-api into my project to inject.. its throwing an exception somewhere.. I've gotta go to bed :(

This was all working sweet several hours ago.. can we not go back to that :P

But seriously, thanks for your help.. i'd be stuffed without this library.

**Comment by slothbag** [comment]
Fixed
