### ISSUE TITLE
IpfsClient.Add throws exception due to malformed JSON response

### ISSUE THREAD

**Issue by slothbag** [TrekDev/net-ipfs-api#6]
A recent change in the IPFS API process for adding files is causing older API clients to receive double JSON resultsets like this:

```
{"Name":"file1.jpg","Bytes":12655}
{"Name":"file1.jpg","Hash":"QmSomeValidHashabc"}
```

I had this same error using go-ipfs-api, I updated to latest version and the problem went away.  Unfortunately I didn't find out what the specific cause was,

Is it possible to get this library updated to work with the recent API changes?

**Comment by slothbag** [comment]
Ahh, found the cause.. It seems a progress = false param needs to be included. see https://github.com/ipfs/go-ipfs-api/commit/7c354892da3abdaafb6ac576c100b259b1a73dac

**Comment by TrekDev** [comment]
Hey Slothbag, thanks for letting me know. I'll patch this ASAP on `develop`.

**Comment by TrekDev** [comment]
@slothbag, I've pushed a quick fix to `develop`. Can you check it works on yours before I merge to `master`.

**Comment by slothbag** [comment]
Yeah, looks good! Tried it out and works. Thanks.
