### ISSUE TITLE
Download the file using Hashkey

### ISSUE THREAD

**Issue by pbpraveen1988** [TrekDev/net-ipfs-api#7]
Hello @TrekDev ,

I like your library and i am using it and i want to download the file using hash key and also want to show the peers and downloading progress in %, can you guide me on this issue.

Thank You

**Comment by TrekDev** [comment]
Showing peers and downloading a file is easy:

```
var client = new IpfsClient();

var peers = await ipfs.Swarm.Peers(); // Gives you an ICollection of multiaddresses.

Stream outputStream = await ipfs.Cat("Qm...");
// Write outputStream to a byte[] or file here.
```

To show download percentage you can inject the `IpfsClient` with your own `HttpClient` which has your own Handler to show download completion as shown [here](http://stackoverflow.com/a/20665200)

```
HttpClient httpClient; // httpClient with our handler.
var ifps = new IpfsClient(new Uri("http://127.0.0.1:5001"), httpClient);
```

**Comment by pbpraveen1988** [comment]
Hello @TrekDev ,

Thank You for the solution , one question , 
var peers = await client.Swarm.Peers();

will search for particular file peer or peer is related to something for all files

**Comment by TrekDev** [comment]
@pbpraveen1988 I don't understand the question.

**Comment by timothyparez** [comment]
@pbpraveen1988 it will list all peers with opnen connections.  
It does not allow you to specifically list peers hosting a certain file.

Reference: https://ipfs.io/docs/commands/#ipfs-swarm-peers
