### ISSUE TITLE
Recompile all project for .NET 3.5?

### ISSUE THREAD

**Issue by Vytek** [TrekDev/net-ipfs-api#9]
Is it possibile to recompile all the project for .NET 3.5? I would like to use this library in Unity! But Unity 3D engine use only Mono runtime equivalent to .NET 3.5

Please Help ;-)
Thank you in advance.
Regards.

**Comment by TrekDev** [comment]
Hi Vytek. Sure, I'm pretty sure this could be done. Unfortunately I don't have access to a windows machine at the moment, but you should be able to change the project properties to target .NET 3.5.
